Tolet/TOLETApp/Controllers/ToLetPublishesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TOLETApp.Models;

namespace TOLETApp.Controllers
{
    public class ToLetPublishesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToLetPublishes
        public ActionResult Index()
        {
            return View(db.ToLetPublishs.ToList());
        }

        // GET: ToLetPublishes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToLetPublish toLetPublish = db.ToLetPublishs.Find(id);
            if (toLetPublish == null)
            {
                return HttpNotFound();
            }
            return View(toLetPublish);
        }

        // GET: ToLetPublishes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToLetPublishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AreaName,ToLetFromMonth,RoomType,HouseRent,Location,PhoneNumber,Note")] ToLetPublish toLetPublish)
        {
            if (ModelState.IsValid)
            {
                db.ToLetPublishs.Add(toLetPublish);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toLetPublish);
        }

        // GET: ToLetPublishes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToLetPublish toLetPublish = db.ToLetPublishs.Find(id);
            if (toLetPublish == null)
            {
                return HttpNotFound();
            }
            return View(toLetPublish);
        }

        // POST: ToLetPublishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AreaName,ToLetFromMonth,RoomType,HouseRent,Location,PhoneNumber,Note")] ToLetPublish toLetPublish)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toLetPublish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toLetPublish);
        }

        // GET: ToLetPublishes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToLetPublish toLetPublish = db.ToLetPublishs.Find(id);
            if (toLetPublish == null)
            {
                return HttpNotFound();
            }
            return View(toLetPublish);
        }

        // POST: ToLetPublishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToLetPublish toLetPublish = db.ToLetPublishs.Find(id);
            db.ToLetPublishs.Remove(toLetPublish);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tolet/TOLETApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/FooterBottom.css" rel="stylesheet" />
</head>

<body class="wrapper">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BCPoint", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse">


                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>*@
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>
                    <li>@Html.ActionLink(" ", "Index", "Home")</li>


                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Flat", "Create", "ToLetPublishes")</li>
                    <li>@Html.ActionLink("All Flat", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center>
                <p>&copy; @DateTime.Now.Year -RejaKazi02</p>
            </center>
        </footer>
    </div>


</body>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</html>